src/message.rs
=> Inherit from Sized

Cargo.toml
* https://crates.io/keywords/postgres
* https://crates.io/keywords/postgresql
=> Add keywords to improve linkability on crates.io

README.md
https://github.com/sfackler/rust-postgres/pull/173
=> Update README to reflect minimum version change.

src/lib.rs
Apologies for previous noise :)
=> Correct fix for the docs formating #207

src/lib.rs
=> Fix more breakage similar to rust-lang/rust#36340 and 11f118643

postgres/Cargo.toml, tokio-postgres/Cargo.toml
Category `database` is "Database interfaces"
Badge for Travis CI
=> Add categories and badges for Cargo

postgres-shared/src/params/mod.rs, postgres/Cargo.toml, postgres/src/lib.rs, postgres/src/priv_io.rs
=> Add a connect timeout

README.md
Please let me know if you'd prefer this information to be formatted different or go elsewhere in the README!
=> Specify required version of optional crates

postgres/src/notification.rs, postgres/tests/test.rs
Handle the error that is generated when the DB connection goes down instead of panicing with
an unreachable code error. This allows the notification client to retry establishing the
connection instead of crashing the complete program.
I am very new to rust so please advise if this looks wrong to you.
=> Add handling of DB-Errors in Notification processing

Cargo.toml, postgres-shared/src/params/mod.rs, postgres/Cargo.toml, postgres/src/priv_io.rs, postgres/tests/test.rs, tokio-postgres/Cargo.toml, tokio-postgres/src/lib.rs, tokio-postgres/src/stream.rs
=> Support TCP keepalive

postgres-shared/Cargo.toml, postgres-shared/src/types/geo.rs, postgres-shared/src/types/mod.rs, postgres/Cargo.toml, postgres/tests/types/geo.rs, postgres/tests/types/mod.rs, tokio-postgres/Cargo.toml
This PR introduces support for rust-geo version 0.10.
=> Support geo 0.10

.circleci/config.yml, codegen/src/main.rs, tokio-postgres/src/proto/client.rs, tokio-postgres/src/proto/copy_in.rs
Otherwise there's a ton of overhead passing tons of tiny messages over
channels.
=> Buffer copy_in messages

postgres-native-tls/src/test.rs, postgres-openssl/src/test.rs, postgres/src/config.rs, tokio-postgres/src/config.rs, tokio-postgres/src/connect_raw.rs, tokio-postgres/src/prepare.rs, tokio-postgres/tests/test/main.rs
=> Add channel_binding=disable/prefer/require to config

postgres/src/config.rs, tokio-postgres/src/config.rs
=> Expose accessors on Config object

postgres/src/lib.rs, tokio-postgres/src/lib.rs
=> Add documentation for crate features

postgres-types/src/chrono_04.rs, tokio-postgres/tests/test/types/chrono_04.rs
This avoids an overflow panic if the timestamp is the special "infinity"
or "-infinity" value and produces an error instead.
Fix #640.
=> Use checked arithmetic when decoding into chrono types

tokio-postgres/src/error/mod.rs
Before:
```
database error: ERROR: insert or update on table "owner_rels" violates foreign key constraint "owner_rels_cid_fkey"
```
After:
```
database error: ERROR: insert or update on table "owner_rels" violates foreign key constraint "owner_rels_cid_fkey"
DETAIL:  Key (cid)=(4) is not present in table "releases".
```
Warning: this is completely untested except for `cargo check`, I didn't see existing tests for `Display` and docs.rs is still stuck on 0.15.
=> Give a more helpful message on error

tokio-postgres/src/connect.rs
These are just two minor changes "Rustifying" the code.
=> Clean code at connect function

.circleci/config.yml, codegen/src/type_gen.rs, postgres-native-tls/Cargo.toml, postgres-native-tls/src/lib.rs, postgres-openssl/Cargo.toml, postgres-openssl/src/lib.rs, postgres-protocol/src/authentication/sasl.rs, postgres-types/src/lib.rs, postgres-types/src/special.rs, postgres/Cargo.toml, postgres/src/cancel_token.rs, postgres/src/config.rs, postgres/src/connection.rs, postgres/src/notifications.rs, tokio-postgres/Cargo.toml, tokio-postgres/benches/bench.rs, tokio-postgres/src/connect_socket.rs, tokio-postgres/src/maybe_tls_stream.rs, tokio-postgres/src/socket.rs, tokio-postgres/src/tls.rs, tokio-postgres/tests/test/main.rs, tokio-postgres/tests/test/runtime.rs
=> Upgrade to tokio 0.3

postgres/src/connection.rs, postgres/src/test.rs
=> Make postgres::Client Send again

postgres-protocol/src/lib.rs, postgres-protocol/src/types/mod.rs, postgres-types/src/lib.rs, postgres-types/src/pg_lsn.rs, tokio-postgres/tests/test/types/mod.rs
This type will be useful for implementing the replication protocol.
=> PgLsn type.

tokio-postgres/src/client.rs
This PR solves my problem.
Closes #753
=> feat: add method to clear types cache

postgres-types/src/lib.rs
=> Implement BorrowToSql for an additional type.

postgres-protocol/src/message/backend.rs, tokio-postgres/src/lib.rs, tokio-postgres/src/row.rs, tokio-postgres/src/simple_query.rs
It would be helpful for doing some quick debugging
=> derive Debug for SimpleQueryMessage

postgres-protocol/src/message/backend.rs, tokio-postgres/src/error/mod.rs
=> Handle non-UTF8 error fields

postgres-types/src/jiff_02.rs
=> Remove random `dbg!`s

codegen/Cargo.toml, codegen/src/sqlstate.rs, tokio-postgres/Cargo.toml
=> Upgrade `phf*` to v0.13

tokio-postgres/Cargo.toml
=> Update to socket2 v0.6

postgres/src/client.rs, tokio-postgres/src/client.rs
Takes the review suggestions from @tristan957 #1229.
=> Improve `check_connection` doc comment

tokio-postgres/src/client.rs
Simple Query Raw was not exposed which is now exposed allowing for querying rows as text results in a stream.
=> Expose simple query raw method in tokio postgres
