src/error.rs
src/url.rs

This updates rust-postgres to work with the new FromStr in the git master version of rustc.
You might want to wait to merge this until rustc manages to release a new nightly, otherwise Travis will fail all tests.

Update to new FromStr

---

src/url.rs

New rustc has moved path to old_path in preparation for the new path module.
This change switches to old_path to enable rust-postgres to continue to build.

Switch to using old_path for new rustc

---

Cargo.toml

Current openssl version conflicts with [hyper](https://github.com/hyperium/hyper) and [cookie-rs](https://github.com/alexcrichton/cookie-rs). 
I need them both in my [postgres-example](https://github.com/rustless/rustless/tree/master/examples/postgres).

Update openssl version

---

Cargo.toml

since a lot of project like nickle.rs, iron, hyper already upgrade openssl. it's a good idea to update openssl as well.

bump openssl to v0.6

---

src/types/mod.rs
tests/types/mod.rs

This allows more flexible use of ToSql in generic contexts by allowing
references to be used for encoding.

Implement ToSql for &'a T where T: ToSql

---

src/lib.rs
src/url.rs
tests/types/mod.rs

Hi,
This PR cleans up the calls of to_string in method calls. 
We should favor the usage of to_owned as to_string uses the whole formatting machinery just to clone a string. 
Using .to_owned() is lighter on resources.
Thanks for looking into it !

To_String() cleanup for to_owned on method calls

---

README.md

The README indicated `serde` as the feature corresponding to `serde_json::Value`’s FromSql and ToSql implementations, when it is in fact the `serde_json` feature.
The corresponding module documentation gives the right information.
This is my first github pull request ever, please do tell me if I did anything wrong!

Correct misnamed feature in the README

---

src/url.rs
tests/test.rs

I made the mistake of assuming percent encoding would be done internally and hit a panic. This fix checks the result of `Vec::<u8>::from_hex` for invalid hex values that could result from a user passing a password like `%1*`.
Closes #182

Handle malformed percent-encoding

---

src/lib.rs

Fixes #171. See https://github.com/sfackler/rust-postgres/issues/171#issuecomment-219171884.

Ignore InvalidCatalogName errors for pg_catalog queries

---

src/transaction.rs
tests/test.rs

Fixes #179 
This change creates a `Transaction.savepoint` method, which is equivalent
to `Transaction.transaction`, but takes a custom name for the nested
transaction's savepoint name.

Add savepoint method to Transaction

---

src/types/mod.rs
src/types/special.rs
tests/types/chrono.rs
tests/types/time.rs

This patch adds the `types::Date` and `types::Timestamp` enums, which
can represent either a date/timestamp, or positive or negative
infinity.

Add date and timestamp wrappers that can represent infinity

---

src/types/mod.rs
tests/types/mod.rs

Fix empty array conversion

---

Cargo.toml

Uuid 0.3 has been out for a few weeks and supports serde 0.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sfackler/rust-postgres/199)

Support uuid 0.3

---

src/params.rs

Currently one must convert `String`s to `&str` using `.as_str()` in order to invoke `Connection::connect`.
This may be avoided if `String`s refer to the implementation of `&str` for `IntoConnectParams`
Here's an example before and after this change.
Before:
```
let conn = Connection::connect(env::var("DATABASE_URL").unwrap().as_str(), 
TlsMode::None)
```
After:
```
let conn = Connection::connect(env::var("DATABASE_URL").unwrap(), TlsMode::None)
```

Added convenience impl IntoConnectParams for String

---

README.md

The badge looks slightly better on high resolution density displays as an SVG!

Switch build status badge in readme to svg

---

postgres-shared/src/lib.rs
postgres/src/notification.rs
tokio-postgres/src/lib.rs
tokio-postgres/src/test.rs

Support notifications on tokio-postgres

---

postgres/src/lib.rs
postgres/src/rows.rs
postgres/src/stmt.rs
postgres/src/transaction.rs
postgres/tests/test.rs

This allows Rows to outlive a statement and be sent to 'static threads.
Resolves #263.

Make Rows a fully owned type

---

postgres-shared/src/params/mod.rs

I wanted to be able to use ConnectParams as a key of a hash (to do simple connection pooling), so I've added these Derives.

Add Eq, ParialEq and Hash to ConnectParams (etc)

---

tokio-postgres/src/stream.rs

The latest release of tokio-postgres (version "0.3.0") don't build on non unix platform due to a missing error renaming (forgot when error reform was done).

Correct build error on non-unix targets for tokio-postgres

---

README.md

Thought it might be useful for `rust-postgres` users to know about `r2d2-postgres` so dropped a link to it at the bottom of the README in a `See Also` section.
If for some reason this is undesirable just lmk!

Add README link to `r2d2-postgres`

---

tokio-postgres/src/lib.rs
tokio-postgres/src/tls/mod.rs
tokio-postgres/src/tls/openssl.rs

To write bb8 (https://github.com/khuey/bb8) I made a few modifications to tokio_postgres. These do change the exposed interface.
- `Handshake` no longer consumes itself. This wasn't necessary and allows a single `Handshake` to be shared among multiple connections.
- An `is_desynchronized` is added, mirroring the one in sync `postgres`.
- The `TlsMode` enum now holds references, like its equivalent in sync `postgres`. This requires bounding a couple futures to the lifetime of the `TlsMode`. I expect this to be the most controversial part. Since you can still shove your `Handshake` in a `lazy_static!` to get the static lifetime if you really need it I don't think this is a huge issue.

Fixes for bb8

---

.circleci/config.yml
codegen/src/main.rs
codegen/src/type_gen.rs
postgres-shared/src/rows.rs
postgres-shared/src/types/bit_vec.rs
postgres-shared/src/types/chrono.rs
postgres-shared/src/types/eui48.rs
postgres-shared/src/types/geo.rs
postgres-shared/src/types/mod.rs
postgres-shared/src/types/rustc_serialize.rs
postgres-shared/src/types/serde_json.rs
postgres-shared/src/types/special.rs
postgres-shared/src/types/time.rs
postgres-shared/src/types/uuid.rs
postgres/src/lib.rs
postgres/src/rows.rs
postgres/src/transaction.rs
postgres/tests/test.rs
postgres/tests/types/mod.rs
tokio-postgres/src/rows.rs
tokio-postgres/src/test.rs

This allows for in-place deserialization of text and bytea values in
particular.
Row::get_bytes is removed since it previously existed for this use case.
Closes #281

Allow FromSql to borrow from the buffer

---

postgres-protocol/src/types.rs
postgres-shared/src/types/mod.rs

This way it automatically works with versions of postgres that didn't
support null array entries as long as the data doesn't actually have a
null

Automatically determine flags for array serialization

---

README.md

Added person.id to output so that the compiler won't complain that the id field in the structure is never used. I know this isn't a big thing, but warnings like that can cause confusion for new users.

Change example to avoid compiler warning

---

tokio-postgres/src/proto/connect.rs

Someone forgot to handle the non unix case for this match which prevented a build on windows.
A similar bit of code already existed here in line 51 to 56:
https://github.com/sfackler/rust-postgres/blob/5ad78500095c0a9a59533b9164f46edd23cb9e1b/tokio-postgres/src/stream.rs

Handle non unix case in poll_start of PollConnect

---

postgres-shared/Cargo.toml
postgres-shared/src/types/mod.rs
postgres-shared/src/types/serde_json.rs

The purpose of this is to enable more performant serialization and deserialization that does not need to go via the `Value` type.

Add Json wrapper type

---

tokio-postgres/src/lib.rs
tokio-postgres/tests/test.rs

The TransactionBuilder is useful when trying to create a Transaction
around a future which takes ownership of the client. See doc comment
for more details.
See comments on #380 on why the current `transaction()` API does not 
work, as well as the proposed solution implemented here.
---
This allows us to work with the transaction API with minimal changes, although there is some follow-up discussions around how the async API works with connection pooling. 
Namely, creating a clone of the inner `Client` leaves behind untracked state when it is pooled. I think this is a longer discussion though, as the current API allows the user to create `Query`, `Prepare`, and other futures that don't require the `Client` to be present when later executed.

Add a TransactionBuilder struct

---

tokio-postgres/Cargo.toml

Remove now-gone with-openssl from docs metadata.

---

tokio-postgres/src/config.rs

I can backport if you want, I don't know if you plan on updating the old versions.

Omit passwords from debug output

---

postgres-protocol/src/message/frontend.rs
tokio-postgres/src/impls.rs
tokio-postgres/src/lib.rs
tokio-postgres/src/proto/client.rs
tokio-postgres/src/proto/codec.rs
tokio-postgres/src/proto/connect_raw.rs
tokio-postgres/src/proto/connection.rs
tokio-postgres/src/proto/copy_in.rs
tokio-postgres/src/proto/mod.rs
tokio-postgres/tests/test/main.rs

copy_in data was previously copied ~3 times - once into the copy_in
buffer, once more to frame it into a CopyData frame, and once to write
that into the stream.
Our Codec is now a bit more interesting. Rather than just writing out
pre-encoded data, we can also send along unencoded CopyData so they can
be framed directly into the stream output buffer. In the future we can
extend this to e.g. avoid allocating for simple commands like Sync.
This also allows us to directly pass large copy_in input directly
through without rebuffering it.

Avoid copies in copy_in

---

Cargo.toml
postgres-protocol/src/message/backend.rs
tokio-postgres/src/proto/bind.rs
tokio-postgres/src/proto/client.rs
tokio-postgres/src/proto/codec.rs
tokio-postgres/src/proto/connect_raw.rs
tokio-postgres/src/proto/connection.rs
tokio-postgres/src/proto/copy_in.rs
tokio-postgres/src/proto/copy_out.rs
tokio-postgres/src/proto/execute.rs
tokio-postgres/src/proto/mod.rs
tokio-postgres/src/proto/prepare.rs
tokio-postgres/src/proto/query.rs
tokio-postgres/src/proto/responses.rs
tokio-postgres/src/proto/simple_query.rs

Our codec implementation originally just parsed single messages out of
the stream buffer. However, if a query returns a bunch of rows, we're
spending a ton of time shipping those individual messages from the
connection back to the Query stream. Instead, collect blocks of unparsed
messages that are as large as possible and send those back.
This cuts the processing time of the following query in half, from ~10
seconds to ~5:
`SELECT s.n, 'name' || s.n FROM generate_series(0, 9999999) AS s(n)`
At this point, almost all of the remainder of the time is spent parsing
the rows.
cc #450

Send response messages in blocks

---

tokio-postgres/src/lib.rs
tokio-postgres/src/proto/client.rs
tokio-postgres/src/proto/typeinfo.rs
tokio-postgres/src/proto/typeinfo_composite.rs
tokio-postgres/src/proto/typeinfo_enum.rs

The existing methods which take slices of parameters work well when
directly passing a temporary slice (e.g. `c.query(s, &[&15, &"hi"])`,
but becomes limiting in other contexts like when programmatically
building up a query. We now offer methods which take iterators, which
are significantly more flexible for these kinds of use cases.
Because of the weird object safety of `ToSql`, we can't be generic over
`Iterator<Item = impl ToSql>`, but instead have to specifically work
with `Iterator<Item = &dyn ToSql>`. This may require a `.map()` or two
but should still work fine.
Closes #265

Add methods that take iterators of parameters

---

tokio-postgres/src/prepare.rs

Currently this code:
```rust
use futures::{FutureExt, TryStreamExt};
use tokio_postgres::{Error, NoTls};
async fn example() -> Result<(), Error> {
let (mut client, connection) = tokio_postgres::connect("host=localhost user=postgres password=postgres", NoTls).await?;
let connection = connection.map(|r| {
if let Err(e) = r {
eprintln!("connection error: {}", e);
}
});
tokio::spawn(connection);
let stmt = client.prepare("SELECT $1::TEXT").await?;
let rows = client
.query(&stmt, &[&"hello world"])
.try_collect::<Vec<_>>()
.await?;
// Now we can check that we got back the same string we sent over.
let value: &str = rows[0].get(0);
assert_eq!(value, "hello world");
Ok::<(), Error>(())
}
#[tokio::main]
async fn main() {
example().boxed().await.unwrap()
}
```
Fails with the following error:
``` …
```

Make prepare() return a Future that satisfies `Send`.

---

postgres/src/transaction.rs

I believe this was missed in 31855141d2eac62c0b3fff34a5825602c177693d.
Feel free to strip my authorship if more convenient, this is just a tested copy-paste.

Add query_one to postgres::Transaction

---

tokio-postgres/src/connect_raw.rs

Although CockroachDB supports the postgres wire protocol, it doesn't appear to support using the `GMT` timezone (at least not on Windows). However, cockroach does accept `UTC`. This PR provides a way to configure the timezone connection property.
I've left the default as `GMT` but I think `UTC` is probably a better option. The native client defaults to unspecified:
> timezone (string)
> Sets the time zone for displaying and interpreting time stamps. If not explicitly set, the server initializes this variable to the time zone specified by its system environment. See Section 8.5.3 for more information.
https://www.postgresql.org/docs/9.1/runtime-config-client.html

Change connection initialization timezone to UTC

---

codegen/src/type_gen.rs
postgres-types/src/lib.rs
postgres-types/src/type_gen.rs

In order to provide proper caching of statements I need to be able to hash both the `query` and the `parameter_types`. That's why I added `Hash` to the `#[derive(...)]` of `Type` and all other structs it depends on.

Add Hash implementation to Type

---

tokio-postgres/src/query.rs

This fixes #492
I also tried adding this piece of code to `Client::execute_raw` but this did not work because it breaks the `check_send` test.

Add back logging of queries

---

tokio-postgres/src/copy_out.rs

@sfackler looks like these just slipped in from a debugging session?

Remove debugging printlns from copy out protocol

---

tokio-postgres/src/transaction.rs

A simple fix to the transaction API. Not sure why there wasn't any warning from the compiler.

Put unused type parameter back into use

---

postgres/src/cancel_token.rs
postgres/src/client.rs
postgres/src/lib.rs
postgres/src/test.rs
postgres/src/transaction.rs
tokio-postgres/src/cancel_token.rs
tokio-postgres/src/client.rs
tokio-postgres/src/lib.rs
tokio-postgres/src/transaction.rs
tokio-postgres/tests/test/main.rs
tokio-postgres/tests/test/runtime.rs

The tl;dr is that it'd be nice to be able to send cancellation requests when using the synchronous client. This is a first pass at implementing that. Not sure if it's mergeable in its current form, as it relies on exposing some private bits of `tokio-postgres` for the sole use of the `postgres` crate, and then marking those bits as `doc(hidden)`.

Support cancellation in synchronous client

---

postgres/src/client.rs
postgres/src/generic_connection.rs
postgres/src/lib.rs
postgres/src/transaction.rs

I am trying to add back in the generic connection trait that existed for connections and traits in version 0.15.2 but was not put back in when this lib was rebuilt. This work is based on an existing closed PR: https://github.com/sfackler/rust-postgres/pull/433. I wasn't exactly sure where to put the generic connection so I added it in a new file but it could easily be moved to the lib.rs or even client.rs. I also used the old name of GenericConnection instead of GenericClient used in the old PR. All available feedback is requested.

Adding in generic connection trait back to the lib

---

tokio-postgres/src/client.rs
tokio-postgres/src/generic_client.rs
tokio-postgres/src/transaction.rs

This adds `execute_raw`,  `query_one`, `query_opt`, `query_raw`, and `prepare_typed` to the generic trait introduced in #525.
Furthermore, in 1ea8b7b2d467b2da49c94de522dd6ec054b5d159 I attempted to fix the lifetimes (as `&mut` is only required for `transaction()`).
@sfackler I'm not sure if this is the way to go or if you want this in a separate PR, if so, please let me know.

Add missing methods to GenericClient

---

tokio-postgres/src/connect_raw.rs
tokio-postgres/src/connection.rs
tokio-postgres/tests/test/main.rs

NoticeResponses received during the startup flow were previously being
dropped on the floor. Instead stash them away so they can be delivered
to the user after the startup flow is complete.

Don't suppress notices during startup flow

---

postgres/src/client.rs
tokio-postgres/src/client.rs

The examples in the rendered documentation looks like this:
```rust
use tokio_postgres::types::ToSql;
use futures::StreamExt;
let params: Vec<String> = vec![
"first param".into(),
"second param".into(),
];
let mut it = Box::pin(client.query_raw(
"SELECT foo FROM bar WHERE biz = $1 AND baz = $2",
params.iter().map(|p| p as &dyn ToSql),
).await?);
while let Some(row) = it.next().await.transpose()? {
let foo: i32 = row.get("foo");
println!("foo: {}", foo);
}
```
```rust
use postgres::types::ToSql;
use fallible_iterator::FallibleIterator;
let params: Vec<String> = vec![
"first param".into(),
"second param".into(),
];
let mut it = client.query_raw(
"SELECT foo FROM bar WHERE biz = $1 AND baz = $2",
params.iter().map(|p| p as &dyn ToSql),
)?;
while let Some(row) = it.next()? {
let foo: i32 = …
```

Added information on how to use Vec<T> with Client::query_raw

---

postgres-types/src/lib.rs
tokio-postgres/src/client.rs
tokio-postgres/src/row.rs
tokio-postgres/src/statement.rs

I added/modified some of the `Debug` implementations to help me make sense of why some of my queries didn't work as expected (spoiler alert: I had semantic errors in the queries). I thought these additions might be useful to the community.
This commit makes the following changes
- Add an opaque `Debug` impl for `Client`.
- Add a rich `Debug` impl for `Row`.
- Make the `Debug` impl for `Type` clearer.
- Change the `Debug` for `Column` to be slightly neater.

Add Debug impls.

---

postgres-types/Cargo.toml
postgres-types/src/lib.rs
postgres-types/src/time_02.rs
postgres/Cargo.toml
tokio-postgres/Cargo.toml
tokio-postgres/tests/test/types/mod.rs
tokio-postgres/tests/test/types/time_02.rs

This is essentially ported from the `chrono` implementation.

Add support for time-0.2 types

---

postgres/src/copy_out_reader.rs

The COPY OUT protocol allows sending CopyData packets that have no data.
The (synchronous) CopyOutReader needs to be careful not to return an
empty slice in this case, but instead request more data, since an empty
slice is taken to mean EOF.

Don't accidentally return early from CopyOutReader

---

postgres/src/test.rs
postgres/src/transaction.rs
tokio-postgres/src/transaction.rs

Revives #184.
The rewrite for async/await and Tokio accidentally lost functionality
that allowed users to assign specific names to savepoints when using
nested transactions. This functionality had originally been added
in #184 and had been updated in #374.
This commit revives this functionality using a similar scheme to the
one that existed before. This should allow CockroachDB users to update
to the next patch release of version `0.17`.

Re-add savepoint method to Transaction

---

postgres/src/config.rs
postgres/src/connection.rs
postgres/src/test.rs

Right now the behavior is hardcoded to log any received notices at the
info level. Add a `notice_callback` configuration option that permits
installing an arbitrary callback to handle any received notices.
As discussed in #588.

Permit configuring the notice callback

---

postgres-types/Cargo.toml
tokio-postgres/Cargo.toml

The latest version of chrono, v0.4.16, permits removing its dependency
on the long-deprecated time v0.1 crate by disabling the "oldtime"
feature.
For backwards compatibility, chrono is leaving the "oldtime" feature on
by default, so disabling the "oldtime" feature requires disabling all
default features and then re-enabling the one default feature ("clock")
that rust-postgres needs.
Note that this change does not cause any backwards-compatibility
problems for users of rust-postgres. The "oldtime" feature controls only
whether `time_v01::Duration` and `chrono::Duration` are the same type
and does not affect any of the APIs used by rust-postgres.

Disable chrono's "oldtime" feature to drop time v0.1

---

postgres-types/src/serde_json_1.rs

It's a bit unwieldy using the `Json` type as a struct field without
this.  `Json` is 'just data', so I think it's usually appropriate to
consider instances to be cloneable and testable for equivalence.

derive Clone, PartialEq and Eq for postgres_types::Json

---

postgres-types/src/lib.rs
postgres/src/binary_copy.rs
postgres/src/client.rs
postgres/src/generic_client.rs
postgres/src/transaction.rs
tokio-postgres/src/binary_copy.rs
tokio-postgres/src/bind.rs
tokio-postgres/src/client.rs
tokio-postgres/src/generic_client.rs
tokio-postgres/src/query.rs
tokio-postgres/src/transaction.rs

This enables passing iterators of `&dyn ToSql` or `T: ToSql` as the `params` argument to `*_raw` methods.
Adds the a helper trait `BorrowToSql` that is only implemented for both `&dyn ToSql` and `T: ToSql`. This trait shouldn't be implemented by users.
Maybe there's a better name for the trait, I chose it because I works as `Borrow<dyn ToSql>` if that was possible.
Fixes #683

better api for passing parameters to `*_raw` methods

---

postgres/src/config.rs

Fix unix socket location in docs (/var/run/postgresql instead of /var/lib/postgresql)

---

postgres-protocol/src/escape/mod.rs
postgres-protocol/src/escape/test.rs
postgres-protocol/src/lib.rs

Fix #575 
These functions are generally useful, but also useful specifically for PR #696 which needs to include arbitrary identifiers in a SQL string.

Add escape_identifier() and escape_literal().

---

postgres-native-tls/Cargo.toml
postgres-openssl/Cargo.toml
postgres-openssl/src/lib.rs
postgres-protocol/Cargo.toml
postgres-types/Cargo.toml
postgres-types/src/serde_json_1.rs
postgres/Cargo.toml
postgres/src/copy_out_reader.rs
postgres/src/notifications.rs
tokio-postgres/Cargo.toml
tokio-postgres/src/binary_copy.rs
tokio-postgres/src/copy_in.rs

@sfackler this is still waiting on releases of both tokio-openssl and tokio-native-tls that include the Tokio v1.0 bump, but I got tests for tokio-postgres and postgres passing, so figured I'd put this up.

deps: upgrade to tokio v1.0 ecosystem

---

postgres-protocol/src/authentication/sasl.rs
postgres-protocol/src/lib.rs
postgres-protocol/src/password/mod.rs
postgres-protocol/src/password/test.rs

Hashing a password on the client side is useful so that you can set
a user's password without ever sending it in plain text to the
server. This avoids leaking passwords in the log or elsewhere.

Add password module for hashing on the client side.

---

tokio-postgres/src/error/mod.rs

Sometimes application needs to take different action on different kind of errors but there is no easy way to differentiate errors when cause is None (#583).

Make error kind public

---

tokio-postgres/src/generic_client.rs
tokio-postgres/src/transaction.rs

Closes #691
As I mentioned in the issue my reasoning is that methods that don't need to create transactions can take &Client and avoid having to deal with generics or Box<GenericClient> and the overhead of async_trait boxed futures. This way a method that takes &Client can be called when you have a impl GenericClient.

add `client` method to `GenericClient`

---

tokio-postgres/src/client.rs

Fixes #772.
The first commit implements the suggestion from the issue to not overwrite any existing cached statements, which should be enough to fix the bug. The second commit splits the cached type info and the byte buffer to have separate locks, to try and reduce the risk of similar bugs happening again. 
I've also tried to document a few things which I spent some time puzzling out, though they may only make sense to me so I'm happy to back them out.

Fix deadlock when pipelining statements. 

---

postgres-native-tls/src/lib.rs
postgres-openssl/src/lib.rs

The current implementation forwards all read requests to the operating system through the socket causing excessive system calls. The effect is magnified when the underlying `Socket` is wrapped around a TLS implementation.
This commit changes the underlying socket to be read-buffered by default with a buffer size of 16K, following the implementation of the official client.
The effect can be seen from these two `strace` captures:
Many sub 100 byte reads
```
[nix-shell:~/tmp/pg-syscall-test]$ strace -f -e recvfrom ./target/debug/pg-syscall-test
strace: Process 1894582 attached
strace: Process 1894583 attached
strace: Process 1894584 attached
strace: Process 1894585 attached
[pid 1894581] recvfrom(9, "S", 1, 0, NULL, NULL) = 1
[pid 1894581] recvfrom(9, 0x55e5e2808463, 5, 0, NULL, NULL) = -1 …
```

tokio-postgres: buffer sockets to avoid excessive syscalls

---

tokio-postgres/src/row.rs
tokio-postgres/src/simple_query.rs
tokio-postgres/tests/test/main.rs

resolves #650.
Added `SimpleColumn` type in order to ensure further extensibility.

expose SimpleQueryRow's column names

---

postgres-types/src/lib.rs

I had misread the docs around needing to enable a feature flag in order to access the derive macros for postgress types. If I misread it, I figured that others could as well, so I threw together a quick PR to make it more clear.
This is tied to the issue I posted here: [https://github.com/sfackler/rust-postgres/issues/799]

Making Postgres Types Documentation More Explict For Feature Flags

---

.github/workflows/ci.yml
postgres-types/Cargo.toml
postgres-types/src/lib.rs
postgres/Cargo.toml
tokio-postgres/Cargo.toml
tokio-postgres/tests/test/types/mod.rs

Fixes #805 
First I tried using the crate `rustversion` to automatically enable the two impls on newer compilers. However, as far as I understand, it is not possible to conditionally include dependencies based on the compiler version. But I wanted to use [`array-init`](https://crates.io/crates/array-init) as there is no other good way to construct the array element by element. So now I decided to just use a Cargo feature. Some might prefer that anyway because downstream users can declare their requirements more explicitly.
I tested this patch in a project of mine and it seems to work fine. 
Let me know what you think!

Add `FromSql` and `ToSql` impls for arrays (guarded behind feature)

---

tokio-postgres/src/query.rs
tokio-postgres/tests/test/main.rs

We need to explicitly wait for the ReadyForQuery response rather than stopping at CommandComplete or we can miss deferred constraint errors!
Closes #832

Fix commit-time error reporting

---

postgres-derive-test/src/composites.rs
postgres-derive/src/composites.rs
postgres-derive/src/fromsql.rs

Fix handling of raw ident fields in derive

---

postgres-derive-test/src/compile-fail/invalid-transparent.rs
postgres-derive-test/src/compile-fail/invalid-transparent.stderr
postgres-derive-test/src/lib.rs
postgres-derive-test/src/transparent.rs
postgres-derive/src/accepts.rs
postgres-derive/src/fromsql.rs
postgres-derive/src/lib.rs
postgres-derive/src/overrides.rs
postgres-derive/src/tosql.rs
postgres-types/src/lib.rs

- @nolanderc for the original PR: https://github.com/sfackler/rust-postgres-derive/pull/18
```rust
#[derive(ToSql, FromSql)]
#[postgres(transparent)]
struct UserId(i32);
```

Derive transparent

---

postgres-types/src/lib.rs

Related issue: #843 
This allows usage of `Vec<Box<dyn ToSql + Sync>>` & `Vec<Box<dyn ToSql + Sync + Send>>` to be used with `Client.query_raw`
```rust
use futures::TryStreamExt;
fn build_params( ... ) -> Vec<Box<(dyn ToSql + Sync + Send)>> { ... }
async fn query_database() {
let stmt = ....;
let params = build_params( ... );
let rows: Vec<Row> = client.query_raw(&stmt, params).await?.try_collect().await?;
}
```

Boxed owned query parameters

---

docker/sql_setup.sh
postgres-protocol/Cargo.toml
postgres-protocol/src/types/mod.rs
postgres-protocol/src/types/test.rs
postgres-types/Cargo.toml
postgres-types/src/lib.rs
tokio-postgres/Cargo.toml
tokio-postgres/tests/test/types/mod.rs

This adds [Postgres ltree, lquery and ltxtquery](https://www.postgresql.org/docs/current/ltree.html) support to rust-postgres. For the uninitiated, ltree ("label tree") is a Postgres datatype that follows a dot-notated search path for a given row. Lquery and ltxtquery allow users to search for rows that match an ltree. There are many query operators to help traverse the tree in a given query.
There is some commentary in #389 on why we **are not** adding `Inner`s for the three datatypes. In summary, because `ltree` is an extension (one that ships with Postgres), it's Oids are not static like many other datatypes. This renders the `Inner` loading by Oid unusable and thus we must match on the `Type` name, like we do for `citext`.
Long term motivations for this are to incorporate these …

Add ltree, lquery and ltxtquery support

---

tokio-postgres/src/client.rs

This fixes warnings reported by rust 1.60 when doing the following:
```shell
$ cargo test --manifest-path tokio-postgres/Cargo.toml --no-default-features
```

Hide `tokio_postgres::client::SocketConfig` behind "runtime" feature

---

postgres-types/src/lib.rs

There is a implementation for `&[u8]` but lacking implementation of `[u8; N]` what this PR is try to add.
Waiting for feedback

feat: support [u8; N] as BYTEA

---

postgres-types/src/lib.rs
tokio-postgres/src/query.rs

After looking at @NAlexPear #747 PR  in relation to #746, it looks like it's changing a lot of function signatures exposed by this library (which probably is not desirable).
Here i propose another solution with the basic ideas being:
Provide a struct like this `pub struct Unknown<'a>(pub &'a (dyn ToSql + Sync));`
and amend the `ToSql` trait with `encode_format` which has a default implementation and only `Unknown` overrides it
With this additional functionality, `encode_bind` can selectively switch between binary and text encoding.
As an implementation detail (which can be changed), `Unknown` requires a method to get the string representation of the inner type so i added an additional `as_string` function to the `ToSql` trait and for most of the basic types the function was implemented in …

Implement Unknown encoding for query parameters

---

postgres-types/src/lib.rs

https://github.com/sfackler/rust-postgres/pull/836 has been really useful for my use case, and this PR makes some small improvements to it.
I have a custom type (call it `T`) that `impl`s `ToSql`, and I override `encode_format`. However in some situations I'm working with `&T` or `Option<T>` and I want `to_sql` to use the format that I've specified in `encode_format`. This change ensures that by delegating to `T::encode_format` in these cases.
As well as being useful, I believe this fixes a correctness issue, as these types already delegate to their inner type to implement `to_sql`, so they should do the same for `encode_format` to avoid emitting, e.g., a text encoding that is tagged as binary.
I've also added `[derive(Clone, Copy, Debug)]` to `Format`, as it's a simple enum and this …

Delegate encode_format to T in &T and Option<T>

---

postgres-types/src/lib.rs
tokio-postgres/src/query.rs

#836 has been helpful as a way of pairing parameter types with their encodings, but the `encode_format` method in the `ToSql` trait would be even more useful with the addition of a reference to `Type`. This would enable more granular encoding of parameters based on the types inferred by Postgres during the `prepare` phase, which would be useful when processing payloads from more general type systems like gRPC or JSON.
Since parameter types are already generated by the time `bind()` is called, it's easy to include them as part of the format-generating process. This PR simply adds a `Type` parameter to the `encode_format` method added to `ToSql`, which should not be a breaking change if it can be made before the next release.

Encode Format based on Type

---

postgres/src/config.rs
tokio-postgres/src/cancel_query.rs
tokio-postgres/src/client.rs
tokio-postgres/src/config.rs
tokio-postgres/src/connect.rs
tokio-postgres/src/connect_socket.rs
tokio-postgres/src/keepalive.rs
tokio-postgres/src/lib.rs
tokio-postgres/tests/test/parse.rs

hello. I use tokio-postgres a lot.
I would like to customize interval and retries when keepalive is turned on.
Therefore, I propose to make it possible to specify the keepalive interval and retries in this pull-request.
Previously, the only keepalive parameter was `keepalives_idle`. This time, add `keepalives_interval` and `keepalives_retries`. `keepalives_interval` is available on neither Redox nor Solaris. `keepalives_retries` is available on neither Redox, Solaris nor Windows. This constraint aligns with that of [socket2::TcpKeepalive](https://github.com/rust-lang/socket2/blob/14e99cf989f54478f017a483c6e5905e5f2e55a4/src/lib.rs#L378-L388).
I thought that adding `keepalives_interval` and `keepalives_retries` blindly would increase the number of arguments for the …

Support keepalive interval and retries.

---

postgres-derive-test/src/composites.rs
postgres-derive-test/src/lib.rs
postgres-derive/src/composites.rs
postgres-derive/src/fromsql.rs
postgres-derive/src/tosql.rs

Allows for derivation of FromSql and ToSql for generic types. Borrowed types are allowed for ToSql, but not meaningful to support for FromSql (so not supported). (also noted in #570)
Would you be interested in this change? A test was added. Happy to iterate.

Derive Generic FromSql/ToSql

---

postgres-protocol/src/message/frontend.rs

The PostgreSQL wire protocol has a "Flush" message, which can be used by the clients for long-lived connections. Add a flush() helper for it.

Add flush() to front-end messages

---

tokio-postgres/src/generic_client.rs

`batch_execute` is in both `tokio_postgres::Client` and `tokio_postgres::Transaction` and is therefore present in the non-tokio `postgres::GenericClient` but is missing from `tokio_postgres::GenericClient`.

tokio_postgres: add batch_execute to GenericClient

---

postgres/Cargo.toml

Fixes https://github.com/sfackler/rust-postgres/issues/956. I found this while doing some upgrades for https://github.com/palfrey/wait-for-db, but the problem is reproducible here with `cargo +nightly build -Z minimal-versions` (note that currently bugs out in other ways, as some of the other libraries have issues in their earlier versions)

[bug] futures-util <0.3.14 doesn't have Stream

---

tokio-postgres/src/copy_in.rs
tokio-postgres/src/query.rs
tokio-postgres/src/simple_query.rs

Signed-off-by: Alex Chi <iskyzh@gmail.com>
This PR adds a new `RawStream` for query result in extended protocol. In some cases, users won't know if the query is a DML or DDL beforehand. `RawStream` returns an enum of `Row` or `RowsAffected`, so that users can always retrieve the information they need.
Previously, only `RowStream` or `query` can get the row contents, and `execute` can only get number of rows affected.
This is used in https://github.com/risinglightdb/sqllogictest-rs/pull/151, which correctly adds Postgres extended protocol support for our Rust version of sqllogictest.
This PR also eliminates duplicated code for extracting number of rows from CommandCompleted. Now we have a single function `extract_row_affected` for that.
Thanks for review! @sfackler

feat: add `rows_affected` to RowStream

---

postgres/src/client.rs
tokio-postgres/src/client.rs
tokio-postgres/src/error/mod.rs
tokio-postgres/src/query.rs

Modifies the `query` method and its siblings to return a new error type instead of panicking when the number of provided parameters doesn't match the number of parameters in the statement.
Closes #998.

Make incorrect number of paramaters an error

---

postgres-protocol/src/message/backend.rs

Exposing `Bytes` type can be beneficial as https://github.com/sfackler/rust-postgres/issues/996 suggested.
Regarding high level usage it can be introduced as following pesudo api:
```rust
impl Row {
fn get2<I, T>(&self, idx: &I) -> Result<T, Error>
where
I: RowIndex + fmt::Display,
T: FromSqlOwned,
{
...
}
}
trait FromSqlOwned {
fn from_sql(ty: &Type, raw: &Bytes) -> Result<Self, Box<dyn Error + Sync + Send>>;
}
// new type of Bytes with utf8 encoding check for cheap clone.
struct ByteString(Bytes);
impl FromSqlOwned for ByteString {
fn from_sql(ty: &Type, raw: &Bytes) -> Result<Self, Box<dyn Error + Sync + Send>> {
std::str::from_utf8(raw.as_ref())?
ByteString(raw.clone())  
}
}
```
Closes #996

export Bytes type through DataRowBody::storage_bytes method.

---

tokio-postgres/Cargo.toml
tokio-postgres/src/cancel_query.rs
tokio-postgres/src/client.rs
tokio-postgres/src/config.rs
tokio-postgres/src/connect.rs
tokio-postgres/src/connect_socket.rs

TCP user timeouts are pretty useful, especially in conjunction with the existing connect timeout / keepalive settings. This adds a new config value, allowing us to set a user timeout on the socket similar to the keepalive setting.

wire through knob for TCP user timeout

---

tokio-postgres/src/keepalive.rs

On OpenBSD this part of the API isn't provided by socket2 due to the underlying socket options are not available/supported.

OpenBSD misses some TCP keepalive options

---

postgres-types/src/lib.rs

This PR simplifies the `ToSql` implementation for `&str`. I believe that the following changes greatly improve its readability. Thanks! 🎉

refactor(types): improve readability of `impl ToSql for &str`

---

postgres-types/src/lib.rs
tokio-postgres/src/connect_socket.rs
tokio-postgres/tests/test/types/mod.rs

Fix serialization of oidvector

---

.github/workflows/ci.yml
postgres-types/src/lib.rs

This allows me to use `tokio_postgres::binary_copy::BinaryCopyInWriter` with boxed `ToSql` types that are created by borrowing data from somewhere else (and are therefore not `'static`).

allow `BorrowToSql` for non-static `Box<dyn ToSql>`

---

.github/workflows/ci.yml
Cargo.toml
postgres-protocol/Cargo.toml
tokio-postgres/Cargo.toml
tokio-postgres/src/config.rs
tokio-postgres/src/lib.rs

Adds support for compiling to WASM environments that provide JS via wasm-bindgen. Because there's no standardized socket API the caller must provide a connection that implements `AsyncRead`/`AsyncWrite` to `connect_raw`.
The motivation for this is [an open PR to the Rust framework for Cloudflare Workers](https://github.com/cloudflare/workers-rs/pull/324) where Cloudflare recently announced support for [TCP sockets](https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/).

feat: add support for wasm

---

postgres-derive-test/src/composites.rs
postgres-derive-test/src/enums.rs
postgres-derive/Cargo.toml
postgres-derive/src/case.rs
postgres-derive/src/composites.rs
postgres-derive/src/enums.rs
postgres-derive/src/fromsql.rs
postgres-derive/src/lib.rs
postgres-derive/src/overrides.rs
postgres-derive/src/tosql.rs
postgres-types/src/lib.rs

Related issue: #934 
Adding a `rename_all` attribute to a struct or enum will rename the container's fields/variants according to the rule specified. Similar to serde's `rename_all` but for use with `ToSql` and `FromSql`. 
This removes the need to manually rename each field/variant before inserting/selecting from postgres (especially useful with enums, who's naming standards differ from rust).
Supported rules:
- "lowercase"
- "UPPERCASE"
- "PascalCase"
- "camelCase"
- "snake_case"
- "SCREAMING_SNAKE_CASE"
- "kebab-case"
- "SCREAMING-KEBAB-CASE"
No external dependencies introduced. Case conversion code from [serde](https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs) was used.
Thanks @jakubadamw for the test cases from #952

added `rename_all` container attribute for enums and structs

---

tokio-postgres/Cargo.toml
tokio-postgres/src/cancel_query.rs
tokio-postgres/src/client.rs
tokio-postgres/src/config.rs
tokio-postgres/src/connect.rs
tokio-postgres/src/connect_socket.rs

Implement load balancing

---

postgres-derive-test/src/compile-fail/invalid-allow-mismatch.rs
postgres-derive-test/src/compile-fail/invalid-allow-mismatch.stderr
postgres-derive-test/src/enums.rs
postgres-derive/src/accepts.rs
postgres-derive/src/fromsql.rs
postgres-derive/src/overrides.rs
postgres-derive/src/tosql.rs
postgres-types/src/lib.rs

As discussed on #1023, this PR implements an override/attribute that allows mismatching Rust and Postgres enums.
```rust
#[derive(ToSql, FromSql)]
#[postgres(allow_mismatch)]
enum Mood {
Sad,
Happy,
Meh,
}
```

feat(derive): add `#[postgres(allow_mismatch)]`

---

.github/workflows/ci.yml
postgres/src/config.rs
tokio-postgres/Cargo.toml
tokio-postgres/src/config.rs
tokio-postgres/src/connect_raw.rs

This mimics the behaviour of libpq and some other libraries (see #1024). This commit uses the `whoami` crate, and thus goes as far as defaulting the user to the executing process' user name on all operating systems.
Closes #1024

`tokio-postgres`: Set user to executing process' user by default.

---

postgres-types/src/chrono_04.rs
tokio-postgres/tests/test/types/chrono_04.rs

Fixes the test run failing in https://github.com/sfackler/rust-postgres/actions/runs/6589121392/job/17903210060?pr=1074 for pull request https://github.com/sfackler/rust-postgres/pull/1074
```
error: use of deprecated associated function `chrono::DateTime::<Tz>::from_utc`: Use TimeZone::from_utc_datetime() or DateTime::from_naive_utc_and_offset instead
--> postgres-types/src/chrono_04.rs:43:22
|
43 |         Ok(DateTime::from_utc(naive, Utc))
|                      ^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
error: could not compile `postgres-types` (lib) due to previous error
```

replace deprecated chrono::DateTime::from_utc

---

tokio-postgres/CHANGELOG.md
tokio-postgres/src/prepare.rs
tokio-postgres/src/statement.rs

I want to access the underlying table and column of a query and found those two information not exposed in the `statement::Column` structure.
I also simplified the `Debug` implementation of `Column` by using `r#type` rather than `type_` so `#[derive(Debug)]` can be used. As the argument list grew longer I also removed the `new` method in favor of making all the fields `pub(crate)`.
Should we maybe expose the three remaining fields as well?
- `type_size: i16`
- `type_modifier: i32`
- `format: i16`
I don't have an immediate need for them. They could provide useful in the future, though.
What are your thoughts on using `NonZeroU32` and `NonZeroI16`? I'm not 100% sure if that's really a good choice for the type. Yet it felt somewhat natural to use it as `0` denotes that this information is …

Add table_oid and column_id to column structure of prepared statements

---

postgres-types/src/serde_json_1.rs

Adds a Default impl for `Json<T> where T: Default` allowing for other structs to use the wrapper and implement Default.

feat(types): add default derive to json wrapper

---

.github/workflows/ci.yml
tokio-postgres/src/row.rs

This small quality-of-life improvement changes these errors:
thread '<unnamed>' panicked at /../.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-postgres-0.7.10/src/row.rs:151:25: error retrieving column 0: error deserializing column 0: a Postgres value was `NULL`
to:
thread '<unnamed>' panicked at my-program.rs:100:25: error retrieving column 0: error deserializing column 0: a Postgres value was `NULL`

add #[track_caller] to the Row::get() functions

---

tokio-postgres/src/config.rs
tokio-postgres/src/connect.rs
tokio-postgres/tests/test/parse.rs

Hi!
I've found that there is no option to set `read-only` in `target-session-attrs` for connection to PostgreSQL.  
Please, take a look at this pull request.

Add `ReadOnly` in `TargetSessionAttrs`

---

postgres-types/CHANGELOG.md
postgres-types/src/pg_lsn.rs

[`str::split`](https://doc.rust-lang.org/std/primitive.str.html#method.split) allocates a vector and generates considerably more instructions when compiled than [`str::split_once`](https://doc.rust-lang.org/std/primitive.str.html#method.split_once).
[`u64::from_str_radix(split_lo, 16)`](https://doc.rust-lang.org/std/primitive.u64.html#method.from_str_radix) will error if the `lsn_str` contains more than one `/` so this change should result in the same behavior as the current implementation despite not explicitly checking this.

use `split_once` instead of `split` to parse lsn strings

---

tokio-postgres/src/client.rs

Avoids needing an extra await point and shrinks the future size by around 72 bytes. Incredibly minor, but still. 
Was just looking for places to shrink future sizes in my application and tried this out.

Shrink query_opt/query_one codegen size very slightly

---

tokio-postgres/src/statement.rs

The lack of this common trait bound caused some unpleasantness. For example, the following didn't compile:
let x = OnceLock::new();
let stmt = db.prepare(...)?;
x.set(stmt).expect(...); // returns Result<(), T=Statement> where T: Debug

impl Debug for Statement

---

postgres-protocol/src/message/backend.rs
tokio-postgres/src/row.rs

Derive a `Clone` implementation for `tokio_postgres::Row`.
I want to clone the row. I can't see why I shouldn't be able to, the actual data is stored in `bytes::Bytes`, which is made to be cloned, and the `Statement` (including columns, etc) is behind an `Arc`, which is exactly the same as `bytes::Bytes`.
I could place the row in an `Arc`, but that would be pretty silly since underneath it would be two `Arc`s stored inside another `Arc`.

Derive Clone for Row

---

postgres-protocol/src/lib.rs
postgres-types/src/lib.rs
postgres-types/src/special.rs

- ...::max_value() -> ..::MAX
- delete explicit import of signed integer types

Fix a few nits pointed out by clippy

---

tokio-postgres/CHANGELOG.md
tokio-postgres/src/generic_client.rs

This PR adds the `simple_query` is missing in the GenericClient. Moreover, I made use of this: https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html so that the documentation is easier to follow.

add simple_query to GenericClient in tokio_postgres

---

tokio-postgres/src/config.rs

Using `impl Into<String>` instead of `&str` in a fn arg allows both `&str` and `String` as parameters - thus if the caller already has a String object that it doesn't need, it can pass it in without extra cloning.
The same might be done with the password, but may require closer look.

Avoid extra clone in config if possible

---

tokio-postgres/src/lib.rs
tokio-postgres/src/simple_query.rs
tokio-postgres/tests/test/main.rs

Adds RowDescription to the SimpleQueryMessage to allow column information to be consumed without needing to consume any DataRows
Resolves #1143

Adds RowDescription to the SimpleQueryMessage

---

tokio-postgres/src/client.rs
tokio-postgres/src/transaction_builder.rs

Closes #1127 
Closes #1121 
Closes #1120

Fix cancellation of TransactionBuilder::start

---

tokio-postgres/src/query.rs
tokio-postgres/tests/test/main.rs

If a query returns no data, we receive `Message::NoData`, which signals the completion of the query. However, we treated it as a no-op, leading to processing other messages and eventual failure.
This PR fixes the issue and updates the `query_typed` tests to cover this scenario.

For `query_typed`, deal with the no-data case.

---

tokio-postgres/tests/test/types/chrono_04.rs

`test_date_time_params` and `test_with_special_date_time_params` could fail when run with a non-UTC system time zone.
I encountered these failing tests when writing the tests for jiff.
In Postgres, if no time zone is stated in the input string, then it is assumed to be in system time.<sup>[1]</sup> This means that in these tests, a correctly parsed `DateTime<Utc>` could be compared to an incorrectly offset time.
The offset component is now included in the test strings of these tests. This component is already present in the test strings for `time::OffsetDateTime`.
<sup>[1]</sup> [Postgres docs](https://www.postgresql.org/docs/current/datatype-datetime.html):
>For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as …

Fix `chrono::DateTime<Utc>` tests

---

tokio-postgres/src/config.rs

Seems to have been an oversight when adding that member to the `Config` type

add `load_balance_hosts` to `Debug` impl for `Config`

---

docker-compose.yml
postgres-native-tls/Cargo.toml
postgres-native-tls/src/lib.rs
postgres-native-tls/src/test.rs
postgres-openssl/src/lib.rs
postgres-openssl/src/test.rs
postgres-protocol/src/message/backend.rs
postgres-protocol/src/types/mod.rs
postgres-types/src/lib.rs
postgres/src/config.rs
postgres/src/notifications.rs
postgres/src/transaction.rs
tokio-postgres/src/cancel_query.rs
tokio-postgres/src/cancel_query_raw.rs
tokio-postgres/src/cancel_token.rs
tokio-postgres/src/client.rs
tokio-postgres/src/config.rs
tokio-postgres/src/connect_raw.rs
tokio-postgres/src/connect_tls.rs
tokio-postgres/src/generic_client.rs
tokio-postgres/src/query.rs
tokio-postgres/src/row.rs
tokio-postgres/src/to_statement.rs
tokio-postgres/src/transaction.rs
tokio-postgres/src/transaction_builder.rs
tokio-postgres/tests/test/parse.rs
tokio-postgres/tests/test/types/mod.rs

This patch adds Direct SSL support which is a new feature coming in PostgreSQL 17. With this option, we issue TLS handshake directly without `SslRequest`. This will save a roundtrip on connection opening.
I just follow how libpq is designed, to offer an option `sslnegotiation` to control this behaviour (because it won't work on Postgres 16 or earlier).

feat: sslnegotiation and direct ssl for postgres 17

---

.github/workflows/ci.yml
postgres-protocol/Cargo.toml
postgres-protocol/src/authentication/sasl.rs
postgres-protocol/src/password/mod.rs
tokio-postgres/Cargo.toml
tokio-postgres/src/connect.rs

- **Update rand requirement from 0.8 to 0.9**
- **chore: addressed rand 0.9's deprecations**

fix rand 0.9 deprecations

---

postgres-types/src/time_02.rs
postgres-types/src/time_03.rs
tokio-postgres/tests/test/types/time_03.rs

Trying to get a `PrimitiveDateTime` panics if the value was infinity. This commit fixes the panic.
An infinity test is added, mirroring the existing one for chrono. The test is passing.
I also have an example repo here --> https://github.com/allan2/postgres-time-overflow
This PR is for Issue #1171, but for time 0.3 only.

Fix time 0.3 infinity panics

---

postgres-protocol/src/message/backend.rs
postgres-protocol/src/types/mod.rs
postgres-types/src/lib.rs
postgres/src/notifications.rs
postgres/src/transaction.rs
tokio-postgres/src/query.rs
tokio-postgres/src/row.rs
tokio-postgres/src/to_statement.rs
tokio-postgres/src/transaction.rs
tokio-postgres/src/transaction_builder.rs
tokio-postgres/tests/test/types/mod.rs

This fixes two lints:
- [needless_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_lifetimes)
- [extra_unused_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes)
Clippy should have no errors or warnings after this.
#1197  related, [CI failing](https://github.com/sfackler/rust-postgres/actions/runs/12862110375/job/35856532074) due to pre-existing clippy warnings

Fix clippy lifetimes

---

tokio-postgres/src/connect_socket.rs

This avoids unnecessary errors in environments that don't support the feature.
Closes #1214

Only call set_tcp_user_timeout when enabled

---

postgres-protocol/src/authentication/sasl.rs
postgres-protocol/src/types/mod.rs
postgres/src/config.rs
postgres/src/copy_in_writer.rs
postgres/src/copy_out_reader.rs
tokio-postgres/src/config.rs

`div_ceil` is from Rust v1.73, `io::Error::other` from Rust v1.74.
I've allowed `clippy::doc_overindented_list_items` for now because it made the markdown more readable.

Fix latest clippy warnings

---

postgres-types/src/lib.rs

This otherwise fails at runtime (tested against CockroachDB):
```rust
let mut uuids = Vec::<Uuid>::new();
// ...
db_tx.execute("DELETE FROM mytab WHERE the_uuid_column IN ($1)", &[&uuids])?;
```
```
Error { kind: ToSql(1), cause: Some(WrongType { postgres: Uuid, rust: \"alloc::vec::Vec<uuid::Uuid>\" }) }: error serializing parameter 1: cannot convert between the Rust type `alloc::vec::Vec<uuid::Uuid>` and the Postgres type `uuid`
```
The `= ANY ($1)` construct makes it work.
Since I couldn't find the answer directly, maybe we can add this hint to the documentation? It also applies to [other client libraries](https://stackoverflow.com/questions/53280333/javascript-postgres-db-how-to-use-a-prepared-statement-with-an-array-as-para).

Document type conversion fix for WHERE...IN clauses

---

tokio-postgres/src/connect_tls.rs

Both of the options are not valid in rust-postgres and they are not supported.
Actually rust-postgres deviates from postgres docs by checking the certificate when specifying "require".
related: https://github.com/sfackler/rust-postgres/pull/988
Would it make sense to parse "require-full" into SslMode:Require? That would make it compatible with normal postgres connection URLs
cc @nyurik hi! nice to see you here!

Remove mentions of require-full and require-ca

---

tokio-postgres/src/lib.rs
tokio-postgres/tests/test/main.rs

Addresses two minor issues:
1. Fixes a test for `query_opt` that currently calls `query_one`
2. Adds missing documentation for the `with-cidr-0_3` feature, which though fully-functional is not referenced in the docs

tokio-postgres: Fix test assertion, document existing support for `cidr 0.3`

---

postgres-native-tls/Cargo.toml
postgres-openssl/Cargo.toml
tokio-postgres/Cargo.toml

`futures-util` enables many features by default which make the crate heavy to compile. This disables default features, greatly improving build speed. I've manually verified that the most commonly used features (`alloc` and `std`) weren't necessary for this project.

Disable default features of `futures-util`

---

postgres-types/Cargo.toml
postgres-types/src/serde_json_1.rs
tokio-postgres/Cargo.toml

This project doesn't need `serde-derive` macros, so it can depend on `serde_core` instead of `serde` and be faster to build as a result. More info in https://crates.io/crates/serde_core.

Switch `serde` dependency to `serde_core`

---

tokio-postgres/src/client.rs
tokio-postgres/src/transaction.rs
tokio-postgres/src/transaction_builder.rs

Don't know if this is the correct approach, I just saw that sync close was exposed the same way.
It would be useful to have this exposed so that one can implement their own transaction type with a drop implementation that rolls back.
The reason I would like to implement my own transaction type is that I want to expose it to nodejs via napi-rs, and it is not possible to share things that have a lifetime over that boundary.

expose sync rollback as a private api method

---

tokio-postgres/src/lib.rs

Allows wasm users to import FallibleIterator via tokio-postgres instead
of having to define the dependency themselves.
Fixes #1210

Re-export FallibleIterator from tokio-postgres

---

postgres/src/client.rs
postgres/src/test.rs
tokio-postgres/src/client.rs
tokio-postgres/src/connection.rs
tokio-postgres/src/query.rs
tokio-postgres/tests/test/main.rs

Hi. We noticed that `is_closed()` is not always super effective, especially in the `postgres` crate. I've added a couple utilities to try and improve this state.
Problem 1: `is_closed()` checks if the channel is closed, not if the connection is closed. These can be the same, but currently the channel is only closed when `Connection` is dropped. In `postgres::Client`, `Connection` never gets dropped. Fix is to force close the receiver on terminal state.
Problem 2: The connection will only turn if something happens. Sometimes closure can be silent, so even still it seems open. You only can check it's valid if you try to run a query or if the TCP keepalive triggers. Running a `SELECT 1;` is a common workaround, but in my understanding, a single `SYNC` message is cheaper and doesn't cause any …

improve is_closed effectiveness
